
### Access granted to alice due to existing policy
GET http://localhost:4004/processor/Incidents
Authorization: Basic bob:wonderland

### Access denied to bob due to missing policy
GET http://localhost:4004/odata/v4/admin/$metadata
Authorization: Basic alice:builder